
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Сборка начата 26.01.2024 16:50:00.
      Проект "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:02.54
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.3.1+2badb37d1 for .NET Framework
      Сборка начата 26.01.2024 16:50:03.
      Проект "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:02.22
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/zexar/Documents/\u041c\u043e\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0421++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-dv17gm"
      binary: "C:/Users/zexar/Documents/\u041c\u043e\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0421++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-dv17gm"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-dv17gm'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_d474e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        Сборка начата 26.01.2024 16:50:06.
        Проект "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-dv17gm\\cmTC_d474e.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_d474e.dir\\Debug\\".
          Создание каталога "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-dv17gm\\Debug\\".
          Создание каталога "cmTC_d474e.dir\\Debug\\cmTC_d474e.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_d474e.dir\\Debug\\cmTC_d474e.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d474e.dir\\Debug\\\\" /Fd"cmTC_d474e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.33.31630 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d474e.dir\\Debug\\\\" /Fd"cmTC_d474e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-dv17gm\\Debug\\cmTC_d474e.exe" /INCREMENTAL /ILK:"cmTC_d474e.dir\\Debug\\cmTC_d474e.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-dv17gm/Debug/cmTC_d474e.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-dv17gm/Debug/cmTC_d474e.lib" /MACHINE:X64  /machine:x64 cmTC_d474e.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_d474e.vcxproj -> C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-dv17gm\\Debug\\cmTC_d474e.exe
        FinalizeBuildStatus:
          Файл "cmTC_d474e.dir\\Debug\\cmTC_d474e.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_d474e.dir\\Debug\\cmTC_d474e.tlog\\cmTC_d474e.lastbuildstate".
        Сборка проекта "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-dv17gm\\cmTC_d474e.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:02.12
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/zexar/Documents/\u041c\u043e\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0421++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-pkty4k"
      binary: "C:/Users/zexar/Documents/\u041c\u043e\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u044b \u0421++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-pkty4k"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-pkty4k'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_5fca2.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.3.1+2badb37d1 for .NET Framework
        Сборка начата 26.01.2024 16:50:09.
        Проект "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-pkty4k\\cmTC_5fca2.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_5fca2.dir\\Debug\\".
          Создание каталога "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-pkty4k\\Debug\\".
          Создание каталога "cmTC_5fca2.dir\\Debug\\cmTC_5fca2.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_5fca2.dir\\Debug\\cmTC_5fca2.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_5fca2.dir\\Debug\\\\" /Fd"cmTC_5fca2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.33.31630 для x64
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_5fca2.dir\\Debug\\\\" /Fd"cmTC_5fca2.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-pkty4k\\Debug\\cmTC_5fca2.exe" /INCREMENTAL /ILK:"cmTC_5fca2.dir\\Debug\\cmTC_5fca2.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-pkty4k/Debug/cmTC_5fca2.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/zexar/Documents/Мои проекты С++/zexar1530/Cmake/CMakeFiles/CMakeScratch/TryCompile-pkty4k/Debug/cmTC_5fca2.lib" /MACHINE:X64  /machine:x64 cmTC_5fca2.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_5fca2.vcxproj -> C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-pkty4k\\Debug\\cmTC_5fca2.exe
        FinalizeBuildStatus:
          Файл "cmTC_5fca2.dir\\Debug\\cmTC_5fca2.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_5fca2.dir\\Debug\\cmTC_5fca2.tlog\\cmTC_5fca2.lastbuildstate".
        Сборка проекта "C:\\Users\\zexar\\Documents\\Мои проекты С++\\zexar1530\\Cmake\\CMakeFiles\\CMakeScratch\\TryCompile-pkty4k\\cmTC_5fca2.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:02.13
        
      exitCode: 0
...
